// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWL-t5cVfG1giqj30SWQ0sJUf_VA6HX3o',
    appId: '1:1058169817941:web:f679e013bd4d38c6a6fddc',
    messagingSenderId: '1058169817941',
    projectId: 'chat-app-e42e6',
    authDomain: 'chat-app-e42e6.firebaseapp.com',
    storageBucket: 'chat-app-e42e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfsFvzYW0RD9IoE0QkVhun7OwWCUjjBW8',
    appId: '1:1058169817941:android:e8a5d7f161d87c40a6fddc',
    messagingSenderId: '1058169817941',
    projectId: 'chat-app-e42e6',
    storageBucket: 'chat-app-e42e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsKLjhMFtIGhcJ06qtjzlASVevD6_HHPQ',
    appId: '1:1058169817941:ios:717cb3428b22ce7ea6fddc',
    messagingSenderId: '1058169817941',
    projectId: 'chat-app-e42e6',
    storageBucket: 'chat-app-e42e6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsKLjhMFtIGhcJ06qtjzlASVevD6_HHPQ',
    appId: '1:1058169817941:ios:717cb3428b22ce7ea6fddc',
    messagingSenderId: '1058169817941',
    projectId: 'chat-app-e42e6',
    storageBucket: 'chat-app-e42e6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWL-t5cVfG1giqj30SWQ0sJUf_VA6HX3o',
    appId: '1:1058169817941:web:19cad23aec20b255a6fddc',
    messagingSenderId: '1058169817941',
    projectId: 'chat-app-e42e6',
    authDomain: 'chat-app-e42e6.firebaseapp.com',
    storageBucket: 'chat-app-e42e6.appspot.com',
  );
}
